apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Podのレプリカ数（3つ作る）
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Nginxの公式Dockerイメージ
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
